version: '3'
services:
  postgres:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: lemonpai
      POSTGRES_PASSWORD: Mcfth0519
      PDDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /home/db:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: cache
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /home/cache/redis.conf:/usr/local/etc/redis/redis.conf:rw
      - /home/cache/data:/data:rw
    command: /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf "
