name: release
on:
  push:
    branches:
      - develop
    tags:
      - v*
  
jobs:
  updatedb:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        ip: [118.195.142.167]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: deploy
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ matrix.ip }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          scp_source: ./docker-compose.yml
          scp_target: /home/samurais/

      - name: updatedb
        uses: appleboy/ssh-action@master
        with:
          host: ${{ matrix.ip }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/samurais
            docker stop db
            docker rm db
            docker stop cache
            docker rm cache
            docker-compose up -d

  build:
    needs: [updatedb]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        ip: [118.195.142.167]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: trgz
        run: tar -zcvf release.tgz ./*

      - name: deploy
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ matrix.ip }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          scp_source: ./release.tgz
          scp_target: /home/samurais/

      - name: start
        uses: appleboy/ssh-action@master
        with:
          host: ${{ matrix.ip }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/samurais
            tar zxvf release.tgz
            npm install
            npm run build
            pm2 start


  