name: release
on:
  push:
    tags:
     - v*
  
jobs:
  updatedb:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: cache node_modules
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: update db
        run: npm run db
      
  build:
    runs-on: ${{ matrix.ip }}
    strategy:
      fail-fast: true
      matrix:
        ip: [118.195.142.167]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: cache node_modules
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: build
        run: npm run build

      - name: trgz
        run: tar -zcvf release.tgz ./

      - name: deploy
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          scp_source: ./release.tgz
          scp_target: /home/samurais/


  